services:
    'metaclass_filter_bundle.filter.filter_logic':
        class: 'Metaclass\FilterBundle\Filter\FilterLogic'
        arguments:
            - '@api_platform.filter_locator'
        public: false
        abstract: true
        autoconfigure: false
    'Metaclass\FilterBundle\Filter\FilterLogic':
        '@metaclass_filter_bundle.filter.filter_logic'

